<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var $block \Tigren\Ajaxlogin\Block\Form\Login
 */
?>
<div class="mb-login-popup" style="display:none;">
    <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-login">
        <div class="block block-customer-login">
            <div class="block-title">
                <strong id="block-customer-login-heading" role="heading" aria-level="2">Login</strong>
            </div>
            <form class="form form-login" method="post" id="ajax-login-form" enctype="multipart/form-data" autocomplete="off">
              <?php echo $block->getBlockHtml('formkey'); ?>
                    <div class="field email required">
                        <label class="label" for="email"><span><?php echo __('Email') ?></span></label>
                        <div class="control">
                            <input name="login[username]"
                                   value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                                   id="ajaxlogin-email" type="email" class="input-text" title="<?php echo __('Email') ?>"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?php echo __('Password') ?></span></label>
                        <div class="control">
                            <input name="login[password]"
                                   type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                                   class="input-text" id="ajaxlogin-pass" title="<?php echo __('Password') ?>"
                                   data-validate="{required:true, 'validate-password':true}">
                        </div>
                    </div>
                    <div class="actions forgot-password ">
                    <div class="secondary">
                        <a class="action forgot" href="<?php echo $block->getForgotPasswordUrl() ?>">
                            <span><?php echo __('Forgot Your Password?') ?></span>
                        </a>
                    </div>
                    </div>
                    <div class="actions login-submit">
                        <div class="primary">
                            <button type="submit" class="action submit primary" name="login" id="login">
                                <span><?php echo __('Login') ?></span>
                            </button>
                        </div>
                    </div>
              <?php if ($block->isEnableSocialLogin() && !$block->isLoggedIn()): ?>
                  <div id="social-login">
                      <div class="primary">
                        <?php if ($this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/facebook_appid')) { ?>
                            <button id="facebook-login-btn" type="button" class="action social-login-btn primary">
                                <span><?php echo __('Facebook Login') ?></span>
                            </button>
                        <?php } ?>
                        <?php if ($this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/googleplus_clientid')) { ?>
                            <button id="ggplus-login-btn" type="button" class="action social-login-btn primary">
                                <span><?php echo __('Google+ Login') ?></span>
                            </button>
                        <?php } ?>
                        <?php if ($this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/twitter_consumer_key')
                          && $this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/twitter_consumer_secret')
                        ) {
                          ?>
                            <button id="twitter-login-btn" type="button" class="action social-login-btn primary">
                                <span><?php echo __('Twitter Login') ?></span>
                            </button>
                        <?php } ?>
                      </div>
                  </div>
              <?php endif; ?>

            </form>
        </div>
        <div class="block block-new-customer">
            <div class="block-content" aria-labelledby="block-new-customer-heading">
                <div class="actions-toolbar">
                    <div class="primary">
                        You don't have an account? <a href="<?php echo $block->getUrl('customer/account/create'); ?>" class="action create"><span><?= $block->escapeHtml(__('Sign Up!')) ?></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
