<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var $block \Tigren\Ajaxlogin\Block\Form\Register
 */
?>
<div class="mb-register-popup" style="display:none;">
    <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-register">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Sign Up')) ?></strong>
        </div>
        <form class="form form-create-account mb-login-form-register"
              method="post"
              id="ajax-register-form"
              enctype="multipart/form-data" autocomplete="off">


                <input type="hidden" name="success_url" value="">
                <input type="hidden" name="error_url" value="">
                <div class="field field-name-firstname required">
                    <label class="label" for="firstname">
                        <span><?php echo __('First Name') ?></span>
                    </label>
                    <div class="control">
                        <input type="text" id="firstname" name="firstname" value="" title="First Name"
                               class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                               aria-required="true">
                    </div>
                </div>
                <div class="field field-name-lastname required">
                    <label class="label" for="lastname">
                        <span><?= __('Last Name') ?></span>
                    </label>

                    <div class="control">
                        <input type="text" id="lastname" name="lastname" value="" title="Last Name"
                               class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                               aria-required="true">
                    </div>
                </div>
            <!-- New code for customer group - ewoke innovative solution-->
            <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $groupOptions = $objectManager->get('\Magento\Customer\Model\ResourceModel\Group\Collection')->toOptionArray();
            ?>
            <div class="field group_id required">
                <label class="label" for="group_id">
                    <span>Group</span>
                </label>
                <div class="control">
                    <select id="group_id" name="group_id" class="input-text" title="Group" class="validate-select" data-validate="{required:true}" aria-required="true">
                        <option value="" selected >Select Group</option>
                        <?php foreach($groupOptions as $groupOption): ?>
                         <?php if($groupOption['value']==0): ?>
                            <?php else: ?>
                                <option value="<?php echo $groupOption['value']; ?>" ><?php echo $groupOption['label']; ?></option>
                         <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

<!--            --><?php //$_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
<!--            --><?php //if ($_telephone->isEnabled()): ?>
<!--                --><?//= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
<!--            --><?php //endif ?>


            <div class="field mobile required">
                <label class="label" for="mobile">
                    <span><?= $block->escapeHtml(__('Mobile Number')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="mobile" id="mobile" value="" title="<?= $block->escapeHtmlAttr(__('Mobile Number')) ?>" class="input-text" data-validate="{required:true}">
                </div>
            </div>

            <!-- New code for customer group - ewoke innovative solution-->

            <div class="field required">
                    <label for="customer-email" class="label"><span><span><?= __('Email') ?></span></span></label>
                    <div class="control">
                        <input type="email" name="email" autocomplete="off" id="customer-email" value="" title="Email"
                               class="input-text" data-validate="{required:true, 'validate-email':true}"
                               aria-required="true">
                    </div>
                </div>


                <div class="field password required">
                    <label for="password" class="label"><span><?= __('Password') ?></span></label>
                    <div class="control">
                        <input type="password" name="password" id="password" title="Password" class="input-text"
                               data-password-min-length="8" data-password-min-character-sets="3"
                               data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off"
                               aria-required="true">
                    </div>

                </div>
                <div class="field confirmation required">
                    <label for="password-confirmation" class="label"><span><?= __('Confirm Password') ?></span></label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="Confirm Password"
                               id="password-confirmation" class="input-text"
                               data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                               aria-required="true">
                    </div>
                </div>

            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1"
                       id="is_subscribed" class="checkbox">
                <label for="is_subscribed" class="label"><span><?= __('Sign Up for Newsletter') ?></span></label>
            </div>

            <?php //echo $block->getChildHtml('form.additional.info'); ?>

            <div class="actions mb-style-actions">
                <div class="primary">
                    <button type="submit" class="action submit primary"
                            title="Create Account"><span><?= __('Create an Account') ?></span></button>
                </div>
            </div>
            <div class="actions">
                <div class="secondary">
                    <a class="action forgot" href="<?php echo $block->getUrl('customer/account/forgotpassword'); ?>">
                        <span><?php echo __('Forgot Your Password?') ?></span>
                    </a>
                </div>
                <span> | </span>
                <div class="secondary">You Already have an account?
                    <a class="action back" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                        <span class="mb-back-link"><?php echo __('Login') ?></span>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>