<?php
// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
?>
<?php 
$configData = $block->getConfigData();
$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if($configData->isDealProduct($productId)) : ?>
    <?php
        $deal_final_price_amount = number_format($configData->getDealproductbyId($productId),2);
    ?>
    <span class="special-price um-special-price">
        <span class="price-container price-final_price tax weee">
            <span class="price-label">Special Price</span>
            <span id="product-price-<?php echo $idSuffix; ?>" data-price-amount="<?php echo $deal_final_price_amount; ?>" 
				data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?php echo $configData->getcurrencySymbol().''.$deal_final_price_amount; ?></span>
            </span>
        </span>
    </span>
    <span class="old-price um-old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
	
    <?php 
        $price = $block->getSaleableItem()->getPrice();
        $discountType = $configData->getProductUmDiscountType($block->getSaleableItem()->getSku());
        $umDateTo = $configData->getDailydealToDate($block->getSaleableItem()->getSku());
        $umDateFrom = $configData->getDailydealFromDate($block->getSaleableItem()->getSku());
    ?>
	<?php // Show Save and Off value for non bundle and grouped product  ?>
	<div class="um-dd-wrap um-dd-wrap-other-items">
		<?php  if($discountType ==1) :?>
		  <div class="um-dd-save-wrap">
			  <?php $off=(($price-$configData->getDealProductPrice($block->getSaleableItem()->getSku()))* 100)/  $price ; ?>
			  <div class="um-dd-save-per um-discount-type1">
				<span class="dd-discount">Discount</span>
				<span class="dd-save-p"><?php echo number_format($off,2); ?>%</span>
			  </div>
			  <div class="um-dd-save-dol um-discount-type1">
				<span class="dd-save">You Save</span>
				<span class="dd-save-d"><?php echo "" .$configData->getcurrencySymbol()."".number_format($configData->getDealProductDiscountValue($block->getSaleableItem()->getSku()),2); ?></span>
			  </div>
		  </div>
		  <div class="um-dd-discount" id="um-dd-discount">
			  <?php $off=(($price-$configData->getDealProductPrice($block->getSaleableItem()->getSku()))* 100)/  $price ; ?>
			  <div class="um-dd-discount-label">
				   <span class="label"><span class="percent"><?php echo number_format($off,2); ?><span>%</span></span>OFF</span>
			  </div>
		  </div>
		<?php  elseif($discountType ==2) : ?>
		  <div class="um-dd-save-wrap">    
			  <div class="um-dd-save-per um-discount-type2">
				<span class="dd-discount">Discount</span>
				<span class="dd-save-p"><?php echo number_format($configData->getDealProductDiscountValue($block->getSaleableItem()->getSku()),2); ?>%</span>        
				</div>
			  <div class="um-dd-save-dol um-discount-type2">
				<span class="dd-save">You Save</span>
				<span class="dd-save-d"><?php  echo "" .$configData->getcurrencySymbol()."".number_format($price-$deal_final_price_amount); ?></span>                                
			  </div>
		  </div>
		  <div class="um-dd-discount" id="um-dd-discount">
			  <?php $off=(($price-$configData->getDealProductPrice($block->getSaleableItem()->getSku()))* 100)/  $price ; ?>
			  <div class="um-dd-discount-label">
				   <span class="label"><span class="percent"><?php echo number_format($configData->getDealProductDiscountValue($block->getSaleableItem()->getSku()),2); ?><span>%</span></span>OFF</span>
			  </div>
		  </div>
		<?php  endif; ?>
		<div class="um-dd-countdown-timer">
		   <div class="um-dd-timer-wrap">
			<span class="um-dd-timer-label"><i class="fa fa-clock-o" aria-hidden="true"></i><?php /* @noEscape */ echo $configData->getCountdownLabel(); ?></span>
			<div class="um-dd-timer-clock" id="clock-dd-<?php /* @noEscape */ echo $block->getSaleableItem()->getId(); ?>"></div>
		   </div>
		</div>	
		 <script type="text/javascript">
		  require(['jquery', 'jquery.countdown'], function($){
			$(document).ready(function($) {
			  $('#clock-dd-<?php /* @noEscape */ echo $block->getSaleableItem()->getId() ?>').countdown('<?php /* @noEscape */ echo $umDateTo; ?>', function(event) {
				var $this = $(this).html(event.strftime(''
				+ '<div class="um-dd-time"><span class="um-dd-time-value">%w</span> <span class="um-dd-time-label">WEEKS</span></div> '
				+ '<div class="um-dd-time"><span class="um-dd-time-value">%d</span> <span class="um-dd-time-label">DAYS</span></div> '
				+ '<div class="um-dd-time"><span class="um-dd-time-value">%H</span> <span class="um-dd-time-label">HRS</span></div> '
				+ '<div class="um-dd-time"><span class="um-dd-time-value">%M</span> <span class="um-dd-time-label">MIN</span></div> '
				+ '<div class="um-dd-time"><span class="um-dd-time-value">%S</span> <span class="um-dd-time-label">SEC</span></div>'));
			  });
			});
		  });
		 </script>	
	</div>

<?php elseif ($block->hasSpecialPrice()): ?>
    <span class="special-price um-special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span class="old-price um-old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else : ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>
