<?php
/**
 * Created by PhpStorm.
 * User: Ewoke 04
 * Date: 17-Dec-2018
 * Time: 03:45 PM
 */
?>
<?php
/**
 *  General template for displaying group of blocks devided into sections
 */
$group = $this->getGroupName();
$groupCss = $this->getGroupCss();
$groupBehavior = $this->getGroupBehaviour() ? $this->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $this->getGroupChildNames($group, 'getChildHtml')):?>
    <?php $layout = $this->getLayout(); ?>
    <?php foreach ($detailedInfoGroup as $name):?>
        <?php
        $html = $layout->renderElement($name);
        if (!trim($html) && ($this->getUseForce() != true)) continue;
        $alias = $layout->getElementAlias($name);
        $label = $this->getChildData($alias, 'title');
        ?>
        <?php echo $html; ?>
    <?php endforeach;?>
<?php endif; ?>