<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>



<?php $columnsLimit = $this->getColumnsLimit() ? : 0; ?>
<?php $_menu = $this->getHtml('level-top','submenu', $columnsLimit) ?>



<?php if ($_menu): ?>
    <nav class="navigation" role="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php echo $_menu; ?>
            <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
        </ul>
    </nav>
<?php endif; ?>


<script>
    require(['jquery'],function($){
        $(document).ready(function(){
            $('.account-nav-section').hover(function () {
                $(this).addClass('open');
            },function () {
                $(this).removeClass('open');
            })
        });
    });

</script>