<?php if ( $block->enableDisable() ) : ?>
    <?php
    if ( $block->getType() == 'v-bar' ) {
        $width = '93%';
    } else {
        $width = 'auto';
    }
    $fontFamily = $block->headerTextFontFamily();
    $fontFamily = str_replace('+', ' ', $fontFamily);
    $fontFamily = "'" . $fontFamily . "'";
    ?>
    <div id="m-cookienotice"
         class="<?php echo $block->getType(); ?> <?php echo ($block->getType() == 'v-bar') ? $block->getBarPosition() : $block->getBoxPosition(); ?>"
         style="display:none;">
        <div class="m-message title">
            <span class="titlecookie">
            <?php if ( $block->getShow() == 'default' ) :
                echo 'Cookies and Privacy';
            else :
                echo $block->modelTitle();
            endif;
            ?>
                </span>
        </div>
        <div id="message-custom-css" class="m-message custom-css"
             style="width:<?php echo $width ?>;font-size:<?php echo $block->modelMessageSize(); ?>px;font-family:<?php echo $fontFamily; ?>">
            <?php if ( $block->getShow() == 'default' ) :
                echo 'This website use cookies to ensure you get the best user experience on our website.';
            else :
                echo $block->getCustomMessage();
            endif;
            ?>
        </div>
        <div id="action-custom-css" class="m-actions custom-css">
            <a href="javascript:cookieNoticeAccept();" class="m-button m-accept">
                <?php if ( $block->getShow() == 'default' ) :
                    echo "Accept";
                else :
                    echo $block->getCustomAccept();
                endif;
                ?>
            </a>
<!--            <a href="javascript:cookieClose();" class="m-button m-decline">-->
<!--                --><?php //if ( $block->getShow() == 'default' ) :
//                    echo "Decline";
//                else :
//                    echo $block->getCustomDecline();
//                endif;
//                ?>
<!--            </a>-->
            <a href="<?php echo $block->cmsPage(); ?>" target="<?php echo $block->newTab(); ?>" class="m-button">
                <?php if ( $block->getShow() == 'default' ) :
                    echo "Read our Privacy Policy";
                else :
                    echo $block->getCustomMoreInfo();
                endif;
                ?>
            </a>
        </div>
    </div>
    <div id="v-badge" class="v-badge" onClick="showDiv()" style="display:none">Cookie Settings</div>
    <script type="text/javascript">
        var behaviour = <?php echo $block->getBehaviour(); ?>;
        var onScroll ='<?php echo $block->onscroll() ?>';
        var expire ='<?php echo $block->getAutoExpire() ?>';
        if (expire === 0 || expire === '0') {
            expire = 1;
        } else {
            expire =<?php echo $block->getAutoExpire() ?>;
        }

        if (onScroll === 1 || onScroll === '1') {
            window.onscroll = function () {
                if (!jQuery.cookie('cookienotice') || jQuery.cookie('cookienotice') === '0') {
                    custom();
                }
            };
        }

        function custom() {
            if (document.getElementById('m-cookienotice').style.display = 'block') {
                if (behaviour) {
                    var d = new Date();
                    d.setTime(d.getTime() + (behaviour + expire * 24 * 60 * 60 * 1000));
                    var expires = "expires=" + d.toUTCString();

                }
                if (document.body.scrollTop > 150 || document.documentElement.scrollTop > 150) {
                    document.cookie = "cookienotice" + "=" + "true" + ";" + expires + ";path=/";
                    document.getElementById('m-cookienotice').style.display = 'none';
                }
            }
        }

        function showDiv() {
            document.getElementById('m-cookienotice').style.display = "block";
            document.getElementById('v-badge').style.display = 'none';
            <?php if ($block->getAutohide()) : ?>
            setTimeout(function () {
                document.getElementById('m-cookienotice').style.display = 'none';
                document.getElementById('v-badge').style.display = 'block';
            }, <?php echo $block->getAutohide() * 1000; ?>);
            <?php endif; ?>
        }

        function cookieClose() {
            if (behaviour) {
                var d = new Date();
                d.setTime(d.getTime() + (behaviour + expire * 24 * 60 * 60 * 1000));
                var expires = "expires=" + d.toUTCString();
            }
            document.cookie = "cookienotice" + "=" + "0" + ";" + expires + ";path=/";
            document.getElementById('v-badge').style.display = 'block';
            document.getElementById('m-cookienotice').style.display = 'none';
        }

        function cookieNoticeAccept() {
            if (behaviour) {
                var d = new Date();
                d.setTime(d.getTime() + (behaviour + expire * 24 * 60 * 60 * 1000));
                var expires = "expires=" + d.toUTCString();
            }
            document.cookie = "cookienotice" + "=" + "true" + ";" + expires + ";path=/";
            document.getElementById('m-cookienotice').style.display = 'none';
        }

        require([
            'jquery',
            'mage/cookies'
        ], function ($) {
            if ($.cookie('cookienotice') === '0' || $.cookie('cookienotice') === 0){
                document.getElementById('v-badge').style.display = 'block';
            }
            if (!$.cookie('cookienotice')){
                document.getElementById('m-cookienotice').style.display = 'block';
            }
        });

        <?php if ($block->getAutohide()) : ?>
        setTimeout(function () {
            document.getElementById('m-cookienotice').style.display = 'none';
            document.getElementById('v-badge').style.display = 'block';
        }, <?php echo $block->getAutohide() * 1000; ?>);
        <?php endif; ?>
        <?php if ($block->getAutoAccept()) : ?>
        setTimeout(function () {
            cookieNoticeAccept();
        }, <?php echo $block->getAutoAccept() * 1000; ?>);
        <?php endif; ?>
    </script>

<?php endif; ?>
