<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_PushNotifications
 */
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<script>
    importScripts('https://www.gstatic.com/firebasejs/5.5.5/firebase-app.js');
    importScripts('https://www.gstatic.com/firebasejs/5.5.5/firebase-messaging.js');

    firebase.initializeApp({
        messagingSenderId: '<?= $block->getSenderId();  ?>'
    });

    const messaging = firebase.messaging();

    messaging.setBackgroundMessageHandler(function(payload) {
        payload.data.data = JSON.parse(JSON.stringify(payload.data));

        return self.registration.showNotification(payload.data.title, payload.data);
    });

    self.addEventListener('notificationclick', function(event) {
        if (event.notification.data.click_action == '#') {
            return false;
        }

        const target = event.notification.data.click_action || '/';
        event.notification.close();

        event.waitUntil(clients.matchAll({
            type: 'window',
            includeUncontrolled: true
        }).then(function(clientList) {

            for (var i = 0; i < clientList.length; i++) {
                var client = clientList[i];

                if (client.url === target && 'focus' in client) {
                    return client.focus();
                }
            }

            return clients.openWindow(target);
        }));
    });
</script>