<?php
/**
 * Copyright © Ulmod. All rights reserved.
 * See LICENSE.txt for license details.
 */
 
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$dailydealproductCollection = $block->getDailydealEnableProduct();
$outputHelper = $block->getOutputHelper();
?>
<?php if ($block->isEnabled()): ?>
<!--<div class="um-dailydeal-desc-block">-->
<!--   <p>--><?php ///* @noEscape */ echo $block->getDescription(); ?><!--</p>-->
<!--</div>-->
<?php if (!$dailydealproductCollection->count()): ?>
    <div class="message info empty">
		<div><?php /* @noEscape */ echo __('We can\'t find products matching the selection.') ?></div>
	</div>
<?php else: ?>
    <?php //echo $block->getToolbarHtml() ?>
    <?php //echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="dailydeals-deal-view-page products wrapper <?php /* @noEscape */ echo $viewMode; ?> products-<?php /* @noEscape */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items" id="um-dailydeal-items">

		<?php // Loop for Fetch the product Sku from dailydeal collection ?> 			
            <?php foreach($dailydealproductCollection as $dealproduct) : ?>
            
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>            
            <?php  if($block->recentlyDailydeal($dealproduct->getUmProductSku())) : ?>
            
            <?php foreach ($block->getDailyDealProduct($dealproduct->getUmProductSku()) as $_product): ?>
                <?php /* @noEscape */ echo($iterator++ == 1) ? '<li class="item product product-item ">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php                              
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @noEscape */ echo $_product->getProductUrl().'?dailydealproduct=true' ?>"
						class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @noEscape */ echo $_product->getProductUrl().'?dailydealproduct=true' ?>" >
                                <?php /* @noEscape */ echo ucfirst(strtolower($outputHelper->productAttribute($_product, $_product->getName(), 'name'))); ?>
                            </a>
                        </strong>
                      
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                      
                        <?php echo "<div id='dailydeal'>".$block->getProductPrice($_product)."</div>"; ?>
                        <?php /* @noEscape */  ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                       
                        <?php if($_product->getPrice() == 0) : ?>
                            <?php if($_product->getTypeId() != "bundle" && $_product->getTypeId() != "grouped") : ?>
                            <?php $_children = $_product->getTypeInstance()->getUsedProducts($_product);
                               foreach ($_children as $child){                                  
                                    $price = $child->getPrice();
								} 
                            ?>
                            <?php endif; ?>
                        <?php else: ?>
                                <?php $price=$_product->getPrice(); ?>
                        <?php endif;?>

						<?php // Show Save and Off value for bundle and grouped  ?>
                        <?php if($_product->getTypeId() == "bundle" || $_product->getTypeId() == "grouped" ) : ?>
							<div class="um-dd-wrap um-dd-bundle-wrap um-dd-grouped-wrap">
								<?php if($dealproduct->getUmDiscountType() ==1) :?>								
									<div class="um-dd-save-dol um-discount-type1">
									  <span class="dd-save"><?php /* @noEscape */ echo __('You Save') ?></span>
									  <span class="dd-save-d"><?php echo $block->getcurrencySymbol()."".number_format($dealproduct->getUmDiscountAmount(),2); ?></span>
									</div>	
								<?php elseif($dealproduct->getUmDiscountType() ==2) : ?>								
									<div class="um-dd-save-per um-discount-type2">
										 <span class="dd-discount"><?php /* @noEscape */ echo __('Discount') ?></span>
										 <span class="dd-save-p"><?php echo number_format($dealproduct->getUmDiscountAmount(),2); ?>%</span>        
									</div>
									<div class="um-dd-discount" id="um-dd-discount">
										<div class="um-dd-discount-label">
											<span class="label"><span class="percent">
												<?php echo number_format($dealproduct->getUmDiscountAmount(),2); ?>
											<span>%</span></span><?php /* @noEscape */ echo __('OFF') ?></span>
										</div>
									</div>		  
								<?php endif; ?>								
								<?php if ($block->isShowCountdown()): ?>
								   <div class="um-dd-countdown-timer">
									   <div class="um-dd-timer-wrap">
											<span class="um-dd-timer-label">
												<i class="fa fa-clock-o" aria-hidden="true"></i><?php /* @noEscape */ echo $block->getCountdownLabel(); ?>
											</span>
											<div class="um-dd-timer-clock" id="clock-dd-<?php /* @noEscape */ echo $_product->getId(); ?>"></div>
									   </div>
									</div>
									 <script type="text/javascript">
									  require(['jquery', 'jquery.countdown'], function($){
										$(document).ready(function($) {
										  $('#clock-dd-<?php /* @noEscape */ echo $_product->getId() ?>').countdown('<?php /* @noEscape */ echo $dealproduct->getUmDateTo(); ?>', function(event) {
											var $this = $(this).html(event.strftime(''
											+ '<div class="um-dd-time"><span class="um-dd-time-value">%w</span> <span class="um-dd-time-label">WEEKS</span></div> '
											+ '<div class="um-dd-time"><span class="um-dd-time-value">%d</span> <span class="um-dd-time-label">DAYS</span></div> '
											+ '<div class="um-dd-time"><span class="um-dd-time-value">%H</span> <span class="um-dd-time-label">HRS</span></div> '
											+ '<div class="um-dd-time"><span class="um-dd-time-value">%M</span> <span class="um-dd-time-label">MIN</span></div> '
											+ '<div class="um-dd-time"><span class="um-dd-time-value">%S</span> <span class="um-dd-time-label">SEC</span></div>'));
										  });
										});
									  });
									 </script>	
		                        <?php endif; ?> 
							</div>							 
                        <?php endif; ?> 
						 
                    <div>  
                        <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                    <button class="action tocart primary um-deal-button"
                                                            data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}'
                                                            type="button" title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php
                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary um-deal-button"
                                                            data-post='<?php echo $postData; ?>'
                                                            type="button" title="<?php echo __('Add to Cart') ?>">
                                                        <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @noEscape */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @noEscape */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($dailydealproductCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
            <?php  endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
	require(['jquery'], function($){
		$(document.body).addClass('um-daily-deals-widget');
	});
</script>
<?php endif; ?>