<?php
/**
 * Copyright © Ulmod. All rights reserved.
 * See LICENSE.txt for license details.
 */
 
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$dailydealproductCollection = $block->getDailydealEnableProduct();
$outputHelper = $block->getOutputHelper();
$configModel = $block->getConfigModel();
?>
<?php  if ($configModel->isSidebarEnabled()): ?>
	<div class="um-dailydeal-side-block-title">
	   <strong><?php /* @noEscape */ echo $configModel->getSidebarTitle(); ?></strong>
	</div>
	<?php if (!$dailydealproductCollection->count()): ?>
		<div class="message info empty">
			<div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
		</div>
	<?php else: ?>
		<?php
		if ($block->getMode() == 'grid') {
			$viewMode = 'grid';
			$image = 'category_page_grid';
			$showDescription = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		} else {
			$viewMode = 'list';
			$image = 'category_page_list';
			$showDescription = true;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
		}

		 // Position for actions regarding image size changing in vde if needed
		$pos = $block->getPositioned();
		?>
		<div class="um-products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
			<?php $iterator = 1; ?>
			<ol class="um-products list um-items um-product-items" id="um-dailydeal-side-items">
				<?php // Loop to Fetch the product Sku from dailydeal collection ?> 
				<?php foreach($dailydealproductCollection as $dealproduct) : ?>
				
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>				
				<?php if($block->recentlyDailydeal($dealproduct->getUmProductSku())) : ?>				
				<?php foreach ($block->getDailyDealProduct($dealproduct->getUmProductSku()) as $_product): ?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item ">' : '</li><li class="item product product-item">' ?>
					<div class="um-product-item-info" data-container="product-grid">
						<?php								  
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>
						<?php // Product Image ?>
						<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl().'?dailydealproduct=true' ?>" 
							class="product photo product-item-photo" tabindex="-1">
							<?php echo $productImage->toHtml(); ?>
						</a>
						<div class="product details product-item-details">
							<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl().'?dailydealproduct=true' ?>" >
									<?php /* @escapeNotVerified */ echo $outputHelper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
						  
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
						  
							<?php echo "<div id='dailydeal'>".$block->getProductPrice($_product)."</div>"; ?>
							<?php /* @escapeNotVerified */  ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>
						   
							<?php if($_product->getPrice() == 0) : ?>
								<?php if($_product->getTypeId() != "bundle" && $_product->getTypeId() != "grouped") : ?>
								<?php $_children = $_product->getTypeInstance()->getUsedProducts($_product);
								   foreach ($_children as $child){
									  
										$price=$child->getPrice();} 
								?>
								<?php endif; ?>
							<?php else: ?>
									<?php $price=$_product->getPrice(); ?>
							<?php endif;?>

							<?php // Show Save and Off value for bundle and grouped  ?>
							<?php if($_product->getTypeId() == "bundle" || $_product->getTypeId() == "grouped" ) : ?>
								<div class="um-dd-wrap um-dd-bundle-wrap um-dd-grouped-wrap">
									<?php if($dealproduct->getUmDiscountType() ==1) :?>								
										<div class="um-dd-save-dol um-discount-type1">
										  <span class="dd-save"><?php /* @noEscape */ echo __('You Save') ?></span>
										  <span class="dd-save-d"><?php echo $configModel->getcurrencySymbol()."".number_format($dealproduct->getUmDiscountAmount(),2); ?></span>
										</div>	
									<?php elseif($dealproduct->getUmDiscountType() ==2) : ?>								
										<div class="um-dd-save-per um-discount-type2">
											<span class="dd-discount"><?php /* @noEscape */ echo __('Discount') ?></span>
											<span class="dd-save-p"><?php echo number_format($dealproduct->getUmDiscountAmount(),2); ?>%</span>        
										</div>
										<div class="um-dd-discount" id="um-dd-discount">
										  <div class="um-dd-discount-label">
											   <span class="label"><span class="percent"><?php echo number_format($dealproduct->getUmDiscountAmount(),2); ?><span>%</span></span><?php /* @noEscape */ echo __('OFF') ?></span>
										  </div>
										</div>			  
									<?php endif; ?>									
									<?php if($configModel->isShowSidebarCountdown()) : ?>
									   <div class="um-dd-countdown-timer">
										   <div class="um-dd-timer-wrap">
											<span class="um-dd-timer-label"><i class="fa fa-clock-o" aria-hidden="true"></i><?php /* @noEscape */ echo $configModel->getSidebarCountdownLabel(); ?></span>
											<div class="um-dd-timer-clock" id="clock-dd-side-<?php /* @noEscape */ echo $_product->getId(); ?>"></div>
										   </div>
										</div>	
										<script type="text/javascript">
										  require(['jquery', 'jquery.countdown'], function($){
											$(document).ready(function($) {
											  $('#clock-dd-side-<?php /* @noEscape */ echo $_product->getId() ?>').countdown('<?php /* @noEscape */ echo $dealproduct->getUmDateTo(); ?>', function(event) {
												var $this = $(this).html(event.strftime(''
												+ '<div class="um-dd-time"><span class="um-dd-time-value">%w</span> <span class="um-dd-time-label">WEEKS</span></div> '
												+ '<div class="um-dd-time"><span class="um-dd-time-value">%d</span> <span class="um-dd-time-label">DAYS</span></div> '
												+ '<div class="um-dd-time"><span class="um-dd-time-value">%H</span> <span class="um-dd-time-label">HRS</span></div> '
												+ '<div class="um-dd-time"><span class="um-dd-time-value">%M</span> <span class="um-dd-time-label">MIN</span></div> '
												+ '<div class="um-dd-time"><span class="um-dd-time-value">%S</span> <span class="um-dd-time-label">SEC</span></div>'));
											  });
											});
										  });
										 </script>	
									<?php endif; ?> 
								</div>							 
							<?php endif; ?> 							 
						<div>  
							<div class="um-dd-product-item-inner">
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<div class="um-actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" 
													value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
											<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
										<?php endif; ?>
									</div>
								</div>
								<?php if ($showDescription):?>
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $outputHelper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" 
											title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
										   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
									</div>
								<?php endif; ?>
							</div>
						</div>
					</div>
					</div>
					<?php echo($iterator == count($dailydealproductCollection)+1) ? '</li>' : '' ?>
				<?php endforeach; ?>
				<?php endif; ?>
				 <?php endforeach; ?>
			</ol>
		</div>
		<div class="um-side-view-all-deals" id="um-side-view-all-deals">
			<a href="/dailydeals/deal/view/"><?php /* @escapeNotVerified */ echo __('View All Deals') ?></a>
		</div>		
		<?php // echo $block->getToolbarHtml() ?>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
	<?php endif; ?>
	<script type="text/javascript">
		require(['jquery'], function($){
			$(document.body).addClass('um-daily-deals-widget');
		});
	</script>
<?php endif; ?>